### ISSUE TITLE
My dear this is not a demo for how to integrate NatCorder and NatMic

### ISSUE THREAD

**Issue by wukongiii** [olokobayusuf/NatMicCorder-Demo#1]
this is the bait of selling full Nat asset family, look at the required components:
NatCorder 1.3+
NatCam 2.0+
NatMic 1.0+
NatShare 1.1+

First I bought NatCorder and I found the audio quality is awful on Android, I thought our dear author will work it out and put his excellent work in NatCorder. It's ok  our dear author start a new project and make  another $50 , because his effort worth it, but please,  make it simple, I paid another 50$ and I hope a straightforward example to use NatCorder with NatMic, I think most developer buy NatMic because it make  NatCorder complete. Now , i need to figure out how to integrate them myself.

**Comment by wukongiii** [comment]
The namespace  NatCorderU.Core.Timing not exist,  replaced by NatCorderU.Core.Clocks

**Comment by olokobayusuf** [comment]
Hey there. I have inline responses below:
> this is the bait of selling full Nat asset family, look at the required components:

This is meant to be an integration demo for all our assets. That's the entire point: illustrating how all our plugins 'plug-in' together. Also NatShare is free, and NatCam can be replaced with WebCamTexture. So it's not some evil plot that you seem to make it out as.

> First I bought NatCorder and I found the audio quality is awful on Android,

It is important to clarify what 'audio quality' is. NatCorder in no way deteriorates audio quality. **When recording the microphone, any audio glitches you experience are from Unity's `Microphone` API**. Developers have bee facing issues with Unity's mic API for years now, which is why we introduced NatMic. NatMic is an entirely separate product because it is just as independent and extensive for microphone recording as NatCorder is for video recording.

> Now , i need to figure out how to integrate them myself.

That's why this demo exists. Also check out the [integration article](https://medium.com/@olokobayusuf/natcorder-and-natmic-a-crash-course-221e58bc3525).

> The namespace NatCorderU.Core.Timing not exist, replaced by NatCorderU.Core.Clocks

Yup, I'll update this.
